name: Deploy Frontend to S3

on:
  push:
    branches:
      - dev
      - main
      - feat/s3 # 나중에 지우기. 테스트용이라 임시로 추가함.
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting and formatting
        run: npm run lint-and-format
        
      - name: Run tests
        run: npm test -- --watchAll=false
        
      - name: Build application
        run: npm run build
        env:
          CI: false  # 경고를 에러로 취급하지 않도록 설정
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"
      
      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://matajo-frontend/ --delete
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E366AWGFW96RX9 --paths "/*"
          
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_S3_DEPLOY_WEBHOOK }}
          title: "Frontend S3 Deployment Completed"
          description: "Branch: ${{ github.ref_name }}"
          color: 0x0000ff