name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting and formatting
        run: npm run lint-and-format
        
      - name: Build application
        run: npm run build
        env:
          CI: false  # 경고를 에러로 취급하지 않도록 설정
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: matajo
          SENTRY_PROJECT: matajo-s3-test
          REACT_APP_BIZ_KAKAO_REST_API_KEY: ${{ secrets.REACT_APP_BIZ_KAKAO_REST_API_KEY }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_FIREBASE_VAPID_KEY: ${{ secrets.REACT_APP_FIREBASE_VAPID_KEY }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"
      
      - name: Deploy to S3
        run: |
          # HTML 파일 업로드
          aws s3 sync ./build/ s3://matajo-frontend/ --delete --exclude "*" --include "*.html" --content-type "text/html" --cache-control "no-cache"
          
          # JavaScript 파일 업로드
          aws s3 sync ./build/ s3://matajo-frontend/ --delete --exclude "*" --include "*.js" --content-type "text/javascript" --cache-control "max-age=31536000"
          
          # CSS 파일 업로드
          aws s3 sync ./build/ s3://matajo-frontend/ --delete --exclude "*" --include "*.css" --content-type "text/css" --cache-control "max-age=31536000"
          
          # 이미지 파일 업로드
          aws s3 sync ./build/ s3://matajo-frontend/ --delete --exclude "*" --include "*.png" --include "*.jpg" --include "*.jpeg" --include "*.gif" --include "*.ico" --content-type "image/\${filename##*.}" --cache-control "max-age=31536000"
          
          # 나머지 파일 업로드
          aws s3 sync ./build/ s3://matajo-frontend/ --delete --exclude "*.html" --exclude "*.js" --exclude "*.css" --exclude "*.png" --exclude "*.jpg" --exclude "*.jpeg" --exclude "*.gif" --exclude "*.ico"
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E366AWGFW96RX9 --paths "/*"
          
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_S3_DEPLOY_WEBHOOK }}
          title: "Frontend S3 Deployment Completed"
          description: "Branch: ${{ github.ref_name }}"
          color: 0x0000ff